name: Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report.

        Please take the time to read the [README](https://github.com/dtcooper/raspotify#readme) and [Wiki](https://github.com/dtcooper/raspotify/wiki), in particular the [Basic Setup Guide](https://github.com/dtcooper/raspotify/wiki/Basic-Setup-Guide) and the [Troubleshooting](https://github.com/dtcooper/raspotify/wiki/Troubleshooting) section and search though open and closed [isssues](https://github.com/dtcooper/raspotify/issues).
        
        **Duplicates and/or issues that can easily be solved by reading said information will be closed with little to no explanation.**
  - type: checkboxes
    id: device
    attributes:
      label: Compatible Device
      description: Before submitting this issue you have made sure that you are running Raspotify on a compatible device.
      options:
        - label: I'm running Raspotify on a compatible Device
          required: true
  - type: checkboxes
    id: not-a-piv1
    attributes:
      label: Are you sure?
      description: Support for ARMv6 devices (Pi 1 & Pi Zero v1.x) has been dropped.
      options:
        - label: I'm not trying to run Raspotify on a ARMv6 device
          required: true
  - type: checkboxes
    id: os-version
    attributes:
      label: Compatible OS
      description: Before submitting this issue you have made sure that you are running Raspotify on Debian Stable (or at least something based on Debian Stable or newer)
      options:
        - label: I'm running Raspotify on a compatible OS
          required: true
  - type: checkboxes
    id: config
    attributes:
      label: Compatible Configuration
      description: Before submitting this issue you have made sure that you are running Raspotify on a headless system (not a desktop system)
      options:
        - label: I'm running Raspotify on a compatible Configuration
          required: true
  - type: checkboxes
    id: latest-version
    attributes:
      label: Latest Version
      description: Before submitting this issue you have made sure that you are running the latest version of Raspotify
      options:
        - label: I'm running the latest version of Raspotify
          required: true
  - type: checkboxes
    id: not-0-31-8-1
    attributes:
      label: Are you sure?
      description: Before submitting this issue you have made sure that you are not running version 0.31.8.1 on a Pi v1 or Pi Zero?
      options:
        - label: I'm not running Raspotify 0.31.8.1 on a Pi v1 or Pi Zero
          required: true
  - type: checkboxes
    id: due-diligence
    attributes:
      label: Due Diligence
      description: Before submitting this issue you have made sure to read the README, wiki and seach though the issues (open and closed) 
      options:
        - label: I have done my due diligence
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output and/or the contents of /etc/raspotify/crash_report if any ( sudo journalctl -u raspotify -b and sudo cat /etc/raspotify/crash_report )
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
